#!/bin/sh

yes_or_no() {
    while true; do
        read -p "$* [y/n]: " yn
        case $yn in
            [Yy]*) return 0  ;;  
            [Nn]*) echo "Aborted" ; return  1 ;;
        esac
    done
}

message="Do you want to start bloated?"

yes_or_no "$message" && nohup ~/.scripts/startupbloat
