#!/bin/sh
st -c float -e syncclock

org &
st -c float -e update &
nohup librewolf > /dev/null &
# nohup gimp > /dev/null &
# nohup flatpak run net.ankiweb.Anki > /dev/null &
nohup flatpak run io.github.spacingbat3.webcord > /dev/null &
