#!/bin/dash

max_brightness=$(cat /sys/class/backlight/intel_backlight/max_brightness)

if [ "${1#"+"}" != "$1" ]; then
    current_brightness=$(cat /sys/class/backlight/intel_backlight/actual_brightness)
    brightness=$((current_brightness + (max_brightness / 100 * $1)))
    echo $brightness > /sys/class/backlight/intel_backlight/brightness
elif [ "$1" -ge 1 ] || ! [ "$1" -le 100 ]; then
    brightness=$(((max_brightness / 100) * $1))
    echo $brightness > /sys/class/backlight/intel_backlight/brightness
else
    echo "Usage: monitorlight <brightness>\nbrightness: 1-100"
fi

echo $brightness

if [ $(cat /sys/class/backlight/intel_backlight/brightness) -lt 100 ]; then
    brightness=$(((max_brightness / 100) * 1))
    echo $brightness > /sys/class/backlight/intel_backlight/brightness
fi
