#!/bin/sh
cd ~/Notes
emacsclient --create-frame --frame-parameters='(quote (name . "scratchy"))' ~/Notes/index.org &
# st -g 130x37 -c scratchy -e sh -c "echo 'e oaa' | nvim ~/Notes/index.org -s -;" &
# st -g 133x29 -c scratchy -e sh -c "nvim ~/Notes/index.org" &
# st -c scratchy -e sh -c "nvim ~/Notes/index.org" &
# emacsclient -c
