#!/usr/bin/env sh
time=`date +%Y-%m-%d-%I-%M-%S`
geometry=`xrandr | head -n1 | cut -d',' -f2 | tr -d '[:blank:],current'`

dir="`xdg-user-dir PICTURES`/Screenshots"
file="Screenshot_${time}_${geometry}.png"

cd ${dir} && maim -u -f png -s -b 0 | tee "$file" | xclip -selection clipboard -t image/png

notify-send "Copied to clipboard."
feh ${dir}/"$file"
if [ -e "$dir/$file" ]; then
	notify-send "Screenshot Saved."
else
	notify-send "Screenshot Deleted."
fi
