#!/bin/sh
dir="/home/gravity/Media/Pictures/Screenshots"
file="Screenshot_$(date +%Y-%m-%d-%H-%M-%S).png"

cd $dir && maim -u -f png | tee "$file" | xclip -selection clipboard -t image/png

if [ -s "$dir/$file" ]; then
	notify-send -i $dir/$file "Screenshot saved." "Copied to clipboard."
else
	rm "$dir/$file"
	notify-send "Screenshot cancelled."
fi
