#!/bin/sh
trap 'echo "Starting update..."' SIGINT

st -c float -e timeout --signal=SIGINT 10 syncclock

org &
st -c float -e update &
nohup librewolf > /dev/null &
nohup gimp > /dev/null &
nohup flatpak run net.ankiweb.Anki > /dev/null &
nohup flatpak run xyz.armcord.ArmCord > /dev/null &
