#!/bin/sh
(st -c update -e timeout 10 ~/.scripts/syncclockupdate) &

st -g 140x40 -c scratchy -e dash -c "echo ' oaa' | nvim ~/Notes/index.org -s -;" &

firefox &
# flatpak run org.gimp.GIMP &
gimp &
flatpak run net.ankiweb.Anki &
flatpak run xyz.armcord.ArmCord &
