#!/bin/sh

# Check internet connection
# doas rfkill unblock wlan && 
timeout 60 ping -q -c 1 -W 10 google.com >/dev/null 2>&1

if [ $? -eq 2 ] || [ $? -eq 124 ]; then
    notify-send "No internet connection."
    echo "No internet connection."
    exit 1
fi


notify-send "Internet is available, Attempting Clock Sync"
echo "Internet is available, Attempting Clock Sync"

# doas rc-service chrony stop
# doas chronyd -q
#doas rc-service ntp-client restart
# doas $(ntpd -svd; read \n)
doas timeout --signal=SIGINT 15 ntpd -svd
if [ $? -eq 1 ]; then
    notify-send "Sync Failed"
    echo "Sync Failed"
    exit 2
else
    notify-send "Sync Succesful"
    echo "Sync Succesful"
fi
