#!/bin/sh

sesh connect \"$(
	sesh list | fzf-tmux -p 80%,80% \
		--no-sort --border-label ' sesh ' --prompt 'all>  '\
		--header '  ^a all ^t sessions ^x zoxide ^f find ^d tmux kill' \
		--bind 'tab:down,btab:up' \
		--bind 'ctrl-a:change-prompt(all>  )+reload(sesh list)' \
		--bind 'ctrl-t:change-prompt(sessions>  )+reload(sesh list -t)' \
		--bind 'ctrl-x:change-prompt(zoxide>  )+reload(sesh list -z)' \
		--bind 'ctrl-f:change-prompt(find>  )+reload(fd -H -d 2 -t d -E .Trash . ~)' \
		--bind 'ctrl-d:execute(tmux kill-session -t {})+change-prompt(all>  )+reload(sesh list)'
)\"
