#!/bin/sh
[ ! -n "$TMUX" ] && t && return
prev_session=$(tmux display-message -p '#S')
out=$(
	sesh list -i -H | fzf-tmux --ansi -p 80%,80% \
		--no-sort --border-label ' sesh relinquish ' --prompt '⚡ ' \
		--header '  ^a all ^t sessions ^c configs ^z zoxide ^f find ^d delete selected session' \
		--bind 'tab:down,btab:up' \
		--bind 'ctrl-a:change-prompt(⚡ )+reload(sesh list -i -H)' \
		--bind 'ctrl-t:change-prompt(  )+reload(sesh list -i -t)' \
		--bind 'ctrl-f:change-prompt(  )+reload(fd -t d --format {//})' \
		--bind 'ctrl-d:execute(tmux kill-session -t $(echo {} | cut -c 5-))+change-prompt(⚡ )+reload(sesh list -i -H)'
)

sesh connect $out || return
if [ "$out" != "" ]; then
	tmux kill-session -t "$prev_session"
fi
